version: '3'

services:
  virtuoso:
    image: openlink/virtuoso-opensource-7
    ports:
      - "1111:1111" # Expose Virtuoso's HTTP port
      - "8890:8890" # Expose Virtuoso's SPARQL endpoint port
    environment:
      - DBA_PASSWORD=123 # Set a password for the DBA user
    volumes:
      - ./data:/database # Mount a data directory for persistence
