apiVersion: v1
kind: Service
metadata:
  name: virtuoso-service
  labels:
    name: virtuoso-service
    app: virtuoso-gke-deployment
spec:
  type: ClusterIP
  selector:
    name: virtuoso-pod
    app: virtuoso-gke-deployment
  ports:
    - name: virtuoso-http
      port: 1111
      targetPort: 1111
    - name: virtuoso-sparql
      port: 8890
      targetPort: 8890